name: Qodana code scanning
on:
  workflow_dispatch:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches: [ master ]

jobs:
  qodana-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v4.2.2
        with:
          linter: jetbrains/qodana-jvm
          baseline-path: qodana.sarif.json
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
