#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Publish Next

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'doc/**'
      - 'devfiles/**'
      - 'kubernetes/**'
    branches: [ main ]

jobs:
  prepare_environment:
    name: Prepare Environment
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"include\":[$( .github/build-container-matrix.sh -m all )]}"
  build:
    name: ${{ matrix.productCode }} (${{ matrix.version }}) - Publish Next to Quay.io
    needs: prepare_environment
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare_environment.outputs.matrix) }}
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Docker image build and publish
        run: |
          ./projector.sh build \
              --tag ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-next \
              --url ${{ matrix.downloadUrl }} \
              --progress plain \
              --log-level debug
          docker push ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-next
