#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Publish Next

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'doc/**'
      - 'devfiles/**'
      - 'kubernetes/**'
      - 'devfile.yaml'
    branches: [ main ]

jobs:
  prepare_environment:
    name: Prepare Environment
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - id: set-matrix
        run: |
          echo "matrix={\"include\":[$( .github/build-container-matrix.sh -m all )]}" >> $GITHUB_OUTPUT
  build:
    name: ${{ matrix.productCode }} (${{ matrix.version }}) - Publish Next to Quay.io
    needs: prepare_environment
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJson(needs.prepare_environment.outputs.matrix) }}
    steps:
      - name: Clone source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Compute sha revision
        id: short_sha
        run: echo "hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Docker image build and publish
        run: |
          ./projector.sh build \
              --tag ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-next \
              --url ${{ matrix.downloadUrl }} \
              --progress plain \
              --log-level debug
          # publish `repo/name:version-next`
          docker push ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-next
          
          # publish `repo/name:version-shortSha`
          docker tag ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-next ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-${{ steps.short_sha.outputs.hash }}
          docker push ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-${{ steps.short_sha.outputs.hash }}
          
          # publish `repo/name:next`
          if [ ${{ matrix.latest }} == true ]; then
            docker tag ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:${{ matrix.version }}-next ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:next
            docker push ${{ secrets.QUAY_REPOSITORY }}/${{ matrix.dockerImage }}:next
          fi
