#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'doc/**'
      - 'devfiles/**'
      - 'kubernetes/**'
      - 'devfile.yaml'

jobs:
  prepare_environment:
    name: Prepare Environment
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - id: set-matrix
        run: |
          echo "matrix={\"include\":[$( .github/build-container-matrix.sh -m latest )]}" >> $GITHUB_OUTPUT
  build:
    name: ${{ matrix.productCode }} (${{ matrix.version }}) - Projector Docker Build
    needs: prepare_environment
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJson(needs.prepare_environment.outputs.matrix) }}
    steps:
      - name: Clone source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Docker image build
        run: |
          ./projector.sh build \
              --tag ${{ matrix.dockerImage }}:${{ matrix.version }} \
              --url ${{ matrix.downloadUrl }} \
              --progress plain \
              --log-level debug
